export enum SETTINGS_MAIN_BUTTON_CALLBACK {
  NOTIFICATIONS = 'SETTINGS_NOTIFICATIONS',
}

export enum SETTINGS_NOTIFICATIONS_BUTTON_CALLBACK {
  DISABLE = 'NOTIFICATIONS_DISABLE',
  ENABLE = 'NOTIFICATIONS_ENABLE',
  WAKE_UP_TIME = 'NOTIFICATIONS_WAKE_UP_TIME',
  BED_TIME = 'NOTIFICATIONS_BED_TIME',
}
