export enum GLOBAL_VARIABLES {
  BOT_TOKEN = 'BOT_TOKEN',
  DB_HOST = 'DB_HOST',
  DB_USER = 'DB_USER',
  DB_PORT = 'DB_PORT',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DATABASE_URL = 'DATABASE_URL',
  PORT = 'PORT',
  HEROKU_URL = 'HEROKU_URL',
  HEROKU_API_TOKEN = 'HEROKU_API_TOKEN',
  HEROKU_API_URL = 'HEROKU_API_URL',
  BOT_API_URL = 'BOT_API_URL',
  NODE_ENV = 'NODE_ENV',
  TZ = 'TZ',
  ADMIN_CHAT_ID = 'ADMIN_CHAT_ID',
}

export enum ENV {
  DEV = 'develop',
  PROD = 'production',
  STAGING = 'staging',
}
