import { NAVIGATION_CALLBACK } from '../../../models/navigation.model';
import {
  TIPS_DYNAMIC_AFFIRMATION_BUTTON_CALLBACK,
  TIPS_MAIN_BUTTON_CALLBACK,
  TIPS_MUSIC_AFFIRMATION_BUTTON_CALLBACK,
} from '../enums/tips.enum';

export interface TipsCallbacks {
  MAIN: typeof TIPS_MAIN_BUTTON_CALLBACK;
  DYNAMIC_AFFIRMATION: typeof TIPS_DYNAMIC_AFFIRMATION_BUTTON_CALLBACK;
  MUSIC_AFFIRMATION: typeof TIPS_MUSIC_AFFIRMATION_BUTTON_CALLBACK;
}

export interface TipsLabels {
  MAIN: Record<TIPS_MAIN_BUTTON_CALLBACK, string>;
  DYNAMIC_AFFIRMATION: Record<TIPS_DYNAMIC_AFFIRMATION_BUTTON_CALLBACK, string>;
  MUSIC_AFFIRMATION: Record<TIPS_MUSIC_AFFIRMATION_BUTTON_CALLBACK, string>;
}

export interface TipsResponses {
  MAIN: Record<TIPS_MAIN_BUTTON_CALLBACK, string>;
  DYNAMIC_AFFIRMATION: Record<TIPS_DYNAMIC_AFFIRMATION_BUTTON_CALLBACK, string>;
  MUSIC_AFFIRMATION: Record<TIPS_MUSIC_AFFIRMATION_BUTTON_CALLBACK, string>;
}

export interface TipsSceneStructure {
  CALLBACKS: TipsCallbacks;
  LABELS: TipsLabels;
  RESPONSES: TipsResponses;
}

export type TipsSceneContextType = NAVIGATION_CALLBACK | TIPS_MAIN_BUTTON_CALLBACK | TIPS_DYNAMIC_AFFIRMATION_BUTTON_CALLBACK;
