export enum GLOBAL_VARIABLES {
  BOT_TOKEN = 'BOT_TOKEN',
  DB_HOST = 'DB_HOST',
  DB_USER = 'DB_USER',
  DB_PORT = 'DB_PORT',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DATABASE_URL = 'DATABASE_URL',
}
